### PR TITLE
Fix logging format from lighttouch-base (finally !!!).

### PR DESCRIPTION
**Pull request by Hellfar**

### CODE REVIEW

**Comment by Arnaz87** [comment]
What do this has to do with https://github.com/foundpatterns/lighttouch-base/issues/102?

**Comment by Hellfar** [comment]
The logging package was temporarily removed because of its yml format header, now that you merged this package we can re-integrate it in lighttouch.

**Comment by Arnaz87** [comment]
seems weird, it seems like logging went through the same changes as all the other packages, yet none of the others were disabled

**Comment by Hellfar** [comment]
Sorry, I wasn't really clear.
This https://github.com/foundpatterns/lighttouch-base/pull/105/files intends to fix the issue we had with the logging package creating logs in the wrong format.

**Pull request merged**
